language: php

php:
  - 5.6
  - 5.5
  - 5.4

env:
  - LARAVEL_VERSION="4.1.*" TESTBENCH_VERSION="2.1.*"
  - LARAVEL_VERSION="4.2.*" TESTBENCH_VERSION="2.1.*"

before_script:
  - composer self-update
  - mysql -e 'create database translatable_test;'
  - echo "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret'; \n GRANT ALL PRIVILEGES ON * . * TO 'homestead'@'localhost'; \nFLUSH PRIVILEGES; \n" | mysql -u root
  - composer require orchestra/testbench:"$TESTBENCH_VERSION" --dev
  - composer require illuminate/support:"$LARAVEL_VERSION" --dev
  - composer install

script: phpunit --coverage-text
